language: csharp
solution: transporte.sln
sudo: true
install: true
mono: none
dist: bionic
addons:
    snaps:
      - name: dotnet-sdk
        confinement: classic
        channel: 3.1
env:
    global:
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
install:
    - export PATH="$PATH:/home/travis/.dotnet/tools"
    - export PATH="$PATH:$HOME/.local/bin"
    - pip install --user awscli
    - sudo snap alias dotnet-sdk.dotnet dotnet
    - chmod -R a+x .
script:
    - dotnet --version
    - dotnet restore
    - dotnet build
    - dotnet test